export const brands: Record<string, string[]> = {
    Audi: ["A3", "A4", "A6", "A8", "Q3", "Q5", "Q7", "Q8", "R8"],
    BMW: ["3 Series", "5 Series", "7 Series", "X3", "X5", "X7", "M3", "M5"],
    Chevrolet: [
        "Silverado",
        "Malibu",
        "Equinox",
        "Tahoe",
        "Suburban",
        "Camaro",
        "Traverse",
    ],
    Ferrari: [
        "488",
        "Roma",
        "Portofino",
        "F8 Tributo",
        "SF90 Stradale",
        "812 Superfast",
    ],
    Ford: [
        "F-150",
        "Mustang",
        "Explorer",
        "Escape",
        "Edge",
        "Bronco",
        "Focus",
        "Fusion",
    ],
    Honda: ["Civic", "Accord", "CR-V", "Pilot", "Fit", "HR-V", "Odyssey"],
    Hyundai: [
        "Elantra",
        "Sonata",
        "Tucson",
        "Santa Fe",
        "Palisade",
        "Kona",
        "Venue",
    ],
    Jaguar: ["XE", "XF", "XJ", "F-PACE", "E-PACE", "I-PACE", "F-TYPE"],
    Kia: [
        "Rio",
        "Forte",
        "Optima",
        "Sorento",
        "Sportage",
        "Telluride",
        "Stinger",
        "Seltos",
    ],
    Lamborghini: ["Aventador", "Huracan", "Urus", "Sián", "Revuelto"],
    "Land Rover": [
        "Defender",
        "Discovery",
        "Range Rover",
        "Evoque",
        "Velar",
        "Sport",
    ],
    Lexus: ["IS", "ES", "GS", "RX", "NX", "UX", "GX", "LX"],
    Mazda: ["Mazda3", "Mazda6", "CX-3", "CX-5", "CX-9", "MX-5 Miata"],
    "Mercedes-Benz": [
        "A-Class",
        "C-Class",
        "E-Class",
        "S-Class",
        "GLA",
        "GLC",
        "GLE",
        "G-Class",
    ],
    Nissan: [
        "Altima",
        "Maxima",
        "Rogue",
        "Murano",
        "Pathfinder",
        "370Z",
        "GT-R",
        "Sentra",
    ],
    Porsche: [
        "911",
        "Cayenne",
        "Macan",
        "Panamera",
        "Taycan",
        "718 Boxster",
        "718 Cayman",
    ],
    Subaru: [
        "Impreza",
        "Outback",
        "Forester",
        "Crosstrek",
        "Ascent",
        "WRX",
        "BRZ",
    ],
    Tesla: [
        "Model S",
        "Model 3",
        "Model X",
        "Model Y",
        "Cybertruck",
        "Roadster",
    ],
    Toyota: [
        "Corolla",
        "Camry",
        "RAV4",
        "Highlander",
        "Prius",
        "Yaris",
        "Tacoma",
        "Tundra",
    ],
    Volkswagen: [
        "Golf",
        "Jetta",
        "Passat",
        "Tiguan",
        "Atlas",
        "Arteon",
        "ID.4",
    ],
};
